security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false

spring:
  data:
   mongodb:
    host: localhost
    port: 27017
    database: greengourmet
    
   redis:
    host: localhost
    port: 6379
