server:
  port: 8082

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false

spring:
  data:
    mongodb:
      host: mongocluster
      port: 27017
      database: greengourmet
      user: root
      password: iuzkghkuzegdo
    
    redis:
      host: rediscluster
      port: 6379
      password : uhoaizdhukazdadz
