/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ggscanner;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Configuration;

@Configuration
@SpringBootApplication
@EnableAutoConfiguration()
public class Application {

	public static void main(String[] args){
		SpringApplication.run(Application.class, args);
	}

}