<<<<<<< HEAD:src/backend/ggarticleserver/src/main/java/ggarticleserver/Application.java
package ggarticleserver;

=======
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ggscanner;

import ggscanner.config.AppProperties;
>>>>>>> 5381c6ad1fa01ac086e86022a3f88414153b1fc3:src/backend/ggscanner/src/main/java/ggscanner/Application.java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Configuration;

@Configuration
@SpringBootApplication
@EnableAutoConfiguration()
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

}
