version: "3.2"
services:
    frontendservicedev:
        build:
            context: ../../frontend/app
            dockerfile: Dockerfile
        depends_on: 
            - dbtest
        ports:
            - "3000:3000"
        volumes:
            - ../../frontend/app/src:/app/src
            - ../../frontend/app/public:/app/public
        container_name: frontendservicedev

    authservicedev:
        build:
            context: ../../backend/ggauthserver
            dockerfile: Dockerfile
        depends_on: 
            - dbtest
        ports: 
            - "8080:8080"
        container_name: authservicedev
        
    scannerservicedev:
        build:
            context: ../../backend/ggscanner
            dockerfile: Dockerfile
        depends_on: 
            - dbtest
            - mongoserver
        ports: 
            - "8081:8081"
        container_name: scannerservicedev
    
    dbtest:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ougfakugzdaf
        ports: 
            - "3306:3306"
        volumes: # seeds
            - ../db-seeds:/docker-entrypoint-initdb.d
    
    mongoserver:
        image: 'mongo'
        container_name: 'mongoserver'
        environment: 
            - MONGO_INITDB_DATABASE=greengourmet
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=iuzkghkuzegdo
        volumes:
            - ./mongo-volume:/data/db
        ports:
            - '27017-27019:27017-27019'

    cacheserver:
        image: 'bitnami/redis:5.0'
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
        volumes:
            - './redis-volume:/bitnami/redis/data'
        command: /opt/bitnami/scripts/redis/run.sh --maxmemory 200mb --maxmemory-policy allkeys-lru

