version: "3.2"
services:
    frontendservice:
        build:
            context: ../../frontend/app
            dockerfile: Dockerfile
        depends_on: 
            - dbtest
        ports:
            - "3000:3000"
        container_name: frontendservice

    authservice:
        build:
            context: ../../backend/ggauthserver
            dockerfile: Dockerfile
        depends_on: 
            - dbtest
        ports: 
            - "8080:8080"
        container_name: authservice
    
    dbtest:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ougfakugzdaf
        ports: 
            - "3306:3306"
        volumes: # seeds
            - ../db-seeds:/docker-entrypoint-initdb.d

