version: "3.2"
services:
    frontendservicedev:
        build:
            context: ../../frontend/app
            dockerfile: Dockerfile
        depends_on: 
            - dbtest
        ports:
            - "3000:3000"
        volumes:
            - ../../frontend/app/src:/app/src
            - ../../frontend/app/public:/app/public
        container_name: frontendservicedev

    authservicedev:
        build:
            context: ../../backend/ggauthserver
            dockerfile: Dockerfile
        depends_on: 
            - dbtest
        ports: 
            - "8080:8080"
        container_name: authservicedev
    
    dbtest:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ougfakugzdaf
        ports: 
            - "3306:3306"
        volumes: # seeds
            - ../db-seeds:/docker-entrypoint-initdb.d

