spring:
    datasource:
        url: jdbc:mysql://dbtest:3306/greengourmet?serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: ougfakugzdaf
    data:
        mongodb:
        host: mongocluster
        port: 27017
        database: greengourmet
        user: root
        password: iuzkghkuzegdo
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect